//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseMachineUi.ChildReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childClass", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private courseMachineUi.ChildReference.parameterClass[] parameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public courseMachineUi.ChildReference.parameterClass[] parameter {
            get {
                return this.parameterField;
            }
            set {
                if ((object.ReferenceEquals(this.parameterField, value) != true)) {
                    this.parameterField = value;
                    this.RaisePropertyChanged("parameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parameterClass", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parameter")]
    [System.SerializableAttribute()]
    public partial class parameterClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additional_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additional_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additional_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additional_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parameterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional_1 {
            get {
                return this.additional_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.additional_1Field, value) != true)) {
                    this.additional_1Field = value;
                    this.RaisePropertyChanged("additional_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional_2 {
            get {
                return this.additional_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.additional_2Field, value) != true)) {
                    this.additional_2Field = value;
                    this.RaisePropertyChanged("additional_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional_3 {
            get {
                return this.additional_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.additional_3Field, value) != true)) {
                    this.additional_3Field = value;
                    this.RaisePropertyChanged("additional_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional_4 {
            get {
                return this.additional_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.additional_4Field, value) != true)) {
                    this.additional_4Field = value;
                    this.RaisePropertyChanged("additional_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string order {
            get {
                return this.orderField;
            }
            set {
                if ((object.ReferenceEquals(this.orderField, value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parameterId {
            get {
                return this.parameterIdField;
            }
            set {
                if ((this.parameterIdField.Equals(value) != true)) {
                    this.parameterIdField = value;
                    this.RaisePropertyChanged("parameterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childCreate", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childUpdater", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childUpdater : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childDelete", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childDelete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childDeleteAll", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childDeleteAll : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childOptions", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime releaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int releaseDatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime releaseDate {
            get {
                return this.releaseDateField;
            }
            set {
                if ((this.releaseDateField.Equals(value) != true)) {
                    this.releaseDateField = value;
                    this.RaisePropertyChanged("releaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int releaseDates {
            get {
                return this.releaseDatesField;
            }
            set {
                if ((this.releaseDatesField.Equals(value) != true)) {
                    this.releaseDatesField = value;
                    this.RaisePropertyChanged("releaseDates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ChildReference.Ichild")]
    public interface Ichild {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/readString", ReplyAction="http://tempuri.org/Ichild/readStringResponse")]
        courseMachineUi.ChildReference.childClass[] readString(string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/readString", ReplyAction="http://tempuri.org/Ichild/readStringResponse")]
        System.Threading.Tasks.Task<courseMachineUi.ChildReference.childClass[]> readStringAsync(string parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/read", ReplyAction="http://tempuri.org/Ichild/readResponse")]
        courseMachineUi.ChildReference.childClass[] read(System.Guid parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/read", ReplyAction="http://tempuri.org/Ichild/readResponse")]
        System.Threading.Tasks.Task<courseMachineUi.ChildReference.childClass[]> readAsync(System.Guid parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/createString", ReplyAction="http://tempuri.org/Ichild/createStringResponse")]
        string createString(string parentId, string name, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/createString", ReplyAction="http://tempuri.org/Ichild/createStringResponse")]
        System.Threading.Tasks.Task<string> createStringAsync(string parentId, string name, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/create", ReplyAction="http://tempuri.org/Ichild/createResponse")]
        string create(courseMachineUi.ChildReference.childCreate user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/create", ReplyAction="http://tempuri.org/Ichild/createResponse")]
        System.Threading.Tasks.Task<string> createAsync(courseMachineUi.ChildReference.childCreate user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/updateString", ReplyAction="http://tempuri.org/Ichild/updateStringResponse")]
        string updateString(string childId, string name, string user, string parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/updateString", ReplyAction="http://tempuri.org/Ichild/updateStringResponse")]
        System.Threading.Tasks.Task<string> updateStringAsync(string childId, string name, string user, string parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/update", ReplyAction="http://tempuri.org/Ichild/updateResponse")]
        string update(courseMachineUi.ChildReference.childUpdater child);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/update", ReplyAction="http://tempuri.org/Ichild/updateResponse")]
        System.Threading.Tasks.Task<string> updateAsync(courseMachineUi.ChildReference.childUpdater child);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteString", ReplyAction="http://tempuri.org/Ichild/deleteStringResponse")]
        string deleteString(string childId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteString", ReplyAction="http://tempuri.org/Ichild/deleteStringResponse")]
        System.Threading.Tasks.Task<string> deleteStringAsync(string childId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/delete", ReplyAction="http://tempuri.org/Ichild/deleteResponse")]
        string delete(courseMachineUi.ChildReference.childDelete use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/delete", ReplyAction="http://tempuri.org/Ichild/deleteResponse")]
        System.Threading.Tasks.Task<string> deleteAsync(courseMachineUi.ChildReference.childDelete use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteAllString", ReplyAction="http://tempuri.org/Ichild/deleteAllStringResponse")]
        string deleteAllString(string parentId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteAllString", ReplyAction="http://tempuri.org/Ichild/deleteAllStringResponse")]
        System.Threading.Tasks.Task<string> deleteAllStringAsync(string parentId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteAll", ReplyAction="http://tempuri.org/Ichild/deleteAllResponse")]
        string deleteAll(courseMachineUi.ChildReference.childDeleteAll use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/deleteAll", ReplyAction="http://tempuri.org/Ichild/deleteAllResponse")]
        System.Threading.Tasks.Task<string> deleteAllAsync(courseMachineUi.ChildReference.childDeleteAll use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/readOptions", ReplyAction="http://tempuri.org/Ichild/readOptionsResponse")]
        courseMachineUi.ChildReference.childOptions readOptions(System.Guid child, System.Guid user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/readOptions", ReplyAction="http://tempuri.org/Ichild/readOptionsResponse")]
        System.Threading.Tasks.Task<courseMachineUi.ChildReference.childOptions> readOptionsAsync(System.Guid child, System.Guid user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/updateOptions", ReplyAction="http://tempuri.org/Ichild/updateOptionsResponse")]
        string updateOptions(courseMachineUi.ChildReference.childOptions options, System.Guid child, System.Guid user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ichild/updateOptions", ReplyAction="http://tempuri.org/Ichild/updateOptionsResponse")]
        System.Threading.Tasks.Task<string> updateOptionsAsync(courseMachineUi.ChildReference.childOptions options, System.Guid child, System.Guid user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IchildChannel : courseMachineUi.ChildReference.Ichild, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IchildClient : System.ServiceModel.ClientBase<courseMachineUi.ChildReference.Ichild>, courseMachineUi.ChildReference.Ichild {
        
        public IchildClient() {
        }
        
        public IchildClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IchildClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IchildClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IchildClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public courseMachineUi.ChildReference.childClass[] readString(string parent) {
            return base.Channel.readString(parent);
        }
        
        public System.Threading.Tasks.Task<courseMachineUi.ChildReference.childClass[]> readStringAsync(string parent) {
            return base.Channel.readStringAsync(parent);
        }
        
        public courseMachineUi.ChildReference.childClass[] read(System.Guid parent) {
            return base.Channel.read(parent);
        }
        
        public System.Threading.Tasks.Task<courseMachineUi.ChildReference.childClass[]> readAsync(System.Guid parent) {
            return base.Channel.readAsync(parent);
        }
        
        public string createString(string parentId, string name, string user) {
            return base.Channel.createString(parentId, name, user);
        }
        
        public System.Threading.Tasks.Task<string> createStringAsync(string parentId, string name, string user) {
            return base.Channel.createStringAsync(parentId, name, user);
        }
        
        public string create(courseMachineUi.ChildReference.childCreate user) {
            return base.Channel.create(user);
        }
        
        public System.Threading.Tasks.Task<string> createAsync(courseMachineUi.ChildReference.childCreate user) {
            return base.Channel.createAsync(user);
        }
        
        public string updateString(string childId, string name, string user, string parentId) {
            return base.Channel.updateString(childId, name, user, parentId);
        }
        
        public System.Threading.Tasks.Task<string> updateStringAsync(string childId, string name, string user, string parentId) {
            return base.Channel.updateStringAsync(childId, name, user, parentId);
        }
        
        public string update(courseMachineUi.ChildReference.childUpdater child) {
            return base.Channel.update(child);
        }
        
        public System.Threading.Tasks.Task<string> updateAsync(courseMachineUi.ChildReference.childUpdater child) {
            return base.Channel.updateAsync(child);
        }
        
        public string deleteString(string childId, string user) {
            return base.Channel.deleteString(childId, user);
        }
        
        public System.Threading.Tasks.Task<string> deleteStringAsync(string childId, string user) {
            return base.Channel.deleteStringAsync(childId, user);
        }
        
        public string delete(courseMachineUi.ChildReference.childDelete use) {
            return base.Channel.delete(use);
        }
        
        public System.Threading.Tasks.Task<string> deleteAsync(courseMachineUi.ChildReference.childDelete use) {
            return base.Channel.deleteAsync(use);
        }
        
        public string deleteAllString(string parentId, string user) {
            return base.Channel.deleteAllString(parentId, user);
        }
        
        public System.Threading.Tasks.Task<string> deleteAllStringAsync(string parentId, string user) {
            return base.Channel.deleteAllStringAsync(parentId, user);
        }
        
        public string deleteAll(courseMachineUi.ChildReference.childDeleteAll use) {
            return base.Channel.deleteAll(use);
        }
        
        public System.Threading.Tasks.Task<string> deleteAllAsync(courseMachineUi.ChildReference.childDeleteAll use) {
            return base.Channel.deleteAllAsync(use);
        }
        
        public courseMachineUi.ChildReference.childOptions readOptions(System.Guid child, System.Guid user) {
            return base.Channel.readOptions(child, user);
        }
        
        public System.Threading.Tasks.Task<courseMachineUi.ChildReference.childOptions> readOptionsAsync(System.Guid child, System.Guid user) {
            return base.Channel.readOptionsAsync(child, user);
        }
        
        public string updateOptions(courseMachineUi.ChildReference.childOptions options, System.Guid child, System.Guid user) {
            return base.Channel.updateOptions(options, child, user);
        }
        
        public System.Threading.Tasks.Task<string> updateOptionsAsync(courseMachineUi.ChildReference.childOptions options, System.Guid child, System.Guid user) {
            return base.Channel.updateOptionsAsync(options, child, user);
        }
    }
}
