//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseBackGround.parentReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parentClass", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parent")]
    [System.SerializableAttribute()]
    public partial class parentClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private courseBackGround.parentReference.childClass[] childField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid courseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public courseBackGround.parentReference.childClass[] child {
            get {
                return this.childField;
            }
            set {
                if ((object.ReferenceEquals(this.childField, value) != true)) {
                    this.childField = value;
                    this.RaisePropertyChanged("child");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid courseId {
            get {
                return this.courseIdField;
            }
            set {
                if ((this.courseIdField.Equals(value) != true)) {
                    this.courseIdField = value;
                    this.RaisePropertyChanged("courseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="childClass", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.child")]
    [System.SerializableAttribute()]
    public partial class childClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private courseBackGround.parentReference.parameterClass[] parameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public courseBackGround.parentReference.parameterClass[] parameter {
            get {
                return this.parameterField;
            }
            set {
                if ((object.ReferenceEquals(this.parameterField, value) != true)) {
                    this.parameterField = value;
                    this.RaisePropertyChanged("parameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parameterClass", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parameter")]
    [System.SerializableAttribute()]
    public partial class parameterClass : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid childIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid creatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int orderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parameterIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid childId {
            get {
                return this.childIdField;
            }
            set {
                if ((this.childIdField.Equals(value) != true)) {
                    this.childIdField = value;
                    this.RaisePropertyChanged("childId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid creator {
            get {
                return this.creatorField;
            }
            set {
                if ((this.creatorField.Equals(value) != true)) {
                    this.creatorField = value;
                    this.RaisePropertyChanged("creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int order {
            get {
                return this.orderField;
            }
            set {
                if ((this.orderField.Equals(value) != true)) {
                    this.orderField = value;
                    this.RaisePropertyChanged("order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parameterId {
            get {
                return this.parameterIdField;
            }
            set {
                if ((this.parameterIdField.Equals(value) != true)) {
                    this.parameterIdField = value;
                    this.RaisePropertyChanged("parameterId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parentCreate", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parent")]
    [System.SerializableAttribute()]
    public partial class parentCreate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid courseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid courseId {
            get {
                return this.courseIdField;
            }
            set {
                if ((this.courseIdField.Equals(value) != true)) {
                    this.courseIdField = value;
                    this.RaisePropertyChanged("courseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parentUpdate", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parent")]
    [System.SerializableAttribute()]
    public partial class parentUpdate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid courseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid courseId {
            get {
                return this.courseIdField;
            }
            set {
                if ((this.courseIdField.Equals(value) != true)) {
                    this.courseIdField = value;
                    this.RaisePropertyChanged("courseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parentDelete", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parent")]
    [System.SerializableAttribute()]
    public partial class parentDelete : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid parentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid parentId {
            get {
                return this.parentIdField;
            }
            set {
                if ((this.parentIdField.Equals(value) != true)) {
                    this.parentIdField = value;
                    this.RaisePropertyChanged("parentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="parentDeleteAll", Namespace="http://schemas.datacontract.org/2004/07/courseBackGround.parent")]
    [System.SerializableAttribute()]
    public partial class parentDeleteAll : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid courseIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid courseId {
            get {
                return this.courseIdField;
            }
            set {
                if ((this.courseIdField.Equals(value) != true)) {
                    this.courseIdField = value;
                    this.RaisePropertyChanged("courseId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user {
            get {
                return this.userField;
            }
            set {
                if ((this.userField.Equals(value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="parentReference.Iparent")]
    public interface Iparent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/checkString", ReplyAction="http://tempuri.org/Iparent/checkStringResponse")]
        bool checkString(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/checkString", ReplyAction="http://tempuri.org/Iparent/checkStringResponse")]
        System.Threading.Tasks.Task<bool> checkStringAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/check", ReplyAction="http://tempuri.org/Iparent/checkResponse")]
        bool check(System.Guid parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/check", ReplyAction="http://tempuri.org/Iparent/checkResponse")]
        System.Threading.Tasks.Task<bool> checkAsync(System.Guid parentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/readString", ReplyAction="http://tempuri.org/Iparent/readStringResponse")]
        courseBackGround.parentReference.parentClass[] readString(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/readString", ReplyAction="http://tempuri.org/Iparent/readStringResponse")]
        System.Threading.Tasks.Task<courseBackGround.parentReference.parentClass[]> readStringAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/read", ReplyAction="http://tempuri.org/Iparent/readResponse")]
        courseBackGround.parentReference.parentClass[] read(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/read", ReplyAction="http://tempuri.org/Iparent/readResponse")]
        System.Threading.Tasks.Task<courseBackGround.parentReference.parentClass[]> readAsync(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/createString", ReplyAction="http://tempuri.org/Iparent/createStringResponse")]
        string createString(string name, string user, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/createString", ReplyAction="http://tempuri.org/Iparent/createStringResponse")]
        System.Threading.Tasks.Task<string> createStringAsync(string name, string user, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/create", ReplyAction="http://tempuri.org/Iparent/createResponse")]
        string create(courseBackGround.parentReference.parentCreate parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/create", ReplyAction="http://tempuri.org/Iparent/createResponse")]
        System.Threading.Tasks.Task<string> createAsync(courseBackGround.parentReference.parentCreate parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/updateString", ReplyAction="http://tempuri.org/Iparent/updateStringResponse")]
        string updateString(string parentId, string name, string user, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/updateString", ReplyAction="http://tempuri.org/Iparent/updateStringResponse")]
        System.Threading.Tasks.Task<string> updateStringAsync(string parentId, string name, string user, string courseId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/update", ReplyAction="http://tempuri.org/Iparent/updateResponse")]
        string update(courseBackGround.parentReference.parentUpdate parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/update", ReplyAction="http://tempuri.org/Iparent/updateResponse")]
        System.Threading.Tasks.Task<string> updateAsync(courseBackGround.parentReference.parentUpdate parent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteString", ReplyAction="http://tempuri.org/Iparent/deleteStringResponse")]
        string deleteString(string childId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteString", ReplyAction="http://tempuri.org/Iparent/deleteStringResponse")]
        System.Threading.Tasks.Task<string> deleteStringAsync(string childId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/delete", ReplyAction="http://tempuri.org/Iparent/deleteResponse")]
        string delete(courseBackGround.parentReference.parentDelete use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/delete", ReplyAction="http://tempuri.org/Iparent/deleteResponse")]
        System.Threading.Tasks.Task<string> deleteAsync(courseBackGround.parentReference.parentDelete use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteAllString", ReplyAction="http://tempuri.org/Iparent/deleteAllStringResponse")]
        string deleteAllString(string courseId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteAllString", ReplyAction="http://tempuri.org/Iparent/deleteAllStringResponse")]
        System.Threading.Tasks.Task<string> deleteAllStringAsync(string courseId, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteAll", ReplyAction="http://tempuri.org/Iparent/deleteAllResponse")]
        string deleteAll(courseBackGround.parentReference.parentDeleteAll use);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iparent/deleteAll", ReplyAction="http://tempuri.org/Iparent/deleteAllResponse")]
        System.Threading.Tasks.Task<string> deleteAllAsync(courseBackGround.parentReference.parentDeleteAll use);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IparentChannel : courseBackGround.parentReference.Iparent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IparentClient : System.ServiceModel.ClientBase<courseBackGround.parentReference.Iparent>, courseBackGround.parentReference.Iparent {
        
        public IparentClient() {
        }
        
        public IparentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IparentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IparentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IparentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool checkString(string name) {
            return base.Channel.checkString(name);
        }
        
        public System.Threading.Tasks.Task<bool> checkStringAsync(string name) {
            return base.Channel.checkStringAsync(name);
        }
        
        public bool check(System.Guid parentId) {
            return base.Channel.check(parentId);
        }
        
        public System.Threading.Tasks.Task<bool> checkAsync(System.Guid parentId) {
            return base.Channel.checkAsync(parentId);
        }
        
        public courseBackGround.parentReference.parentClass[] readString(string id) {
            return base.Channel.readString(id);
        }
        
        public System.Threading.Tasks.Task<courseBackGround.parentReference.parentClass[]> readStringAsync(string id) {
            return base.Channel.readStringAsync(id);
        }
        
        public courseBackGround.parentReference.parentClass[] read(System.Guid id) {
            return base.Channel.read(id);
        }
        
        public System.Threading.Tasks.Task<courseBackGround.parentReference.parentClass[]> readAsync(System.Guid id) {
            return base.Channel.readAsync(id);
        }
        
        public string createString(string name, string user, string courseId) {
            return base.Channel.createString(name, user, courseId);
        }
        
        public System.Threading.Tasks.Task<string> createStringAsync(string name, string user, string courseId) {
            return base.Channel.createStringAsync(name, user, courseId);
        }
        
        public string create(courseBackGround.parentReference.parentCreate parent) {
            return base.Channel.create(parent);
        }
        
        public System.Threading.Tasks.Task<string> createAsync(courseBackGround.parentReference.parentCreate parent) {
            return base.Channel.createAsync(parent);
        }
        
        public string updateString(string parentId, string name, string user, string courseId) {
            return base.Channel.updateString(parentId, name, user, courseId);
        }
        
        public System.Threading.Tasks.Task<string> updateStringAsync(string parentId, string name, string user, string courseId) {
            return base.Channel.updateStringAsync(parentId, name, user, courseId);
        }
        
        public string update(courseBackGround.parentReference.parentUpdate parent) {
            return base.Channel.update(parent);
        }
        
        public System.Threading.Tasks.Task<string> updateAsync(courseBackGround.parentReference.parentUpdate parent) {
            return base.Channel.updateAsync(parent);
        }
        
        public string deleteString(string childId, string user) {
            return base.Channel.deleteString(childId, user);
        }
        
        public System.Threading.Tasks.Task<string> deleteStringAsync(string childId, string user) {
            return base.Channel.deleteStringAsync(childId, user);
        }
        
        public string delete(courseBackGround.parentReference.parentDelete use) {
            return base.Channel.delete(use);
        }
        
        public System.Threading.Tasks.Task<string> deleteAsync(courseBackGround.parentReference.parentDelete use) {
            return base.Channel.deleteAsync(use);
        }
        
        public string deleteAllString(string courseId, string user) {
            return base.Channel.deleteAllString(courseId, user);
        }
        
        public System.Threading.Tasks.Task<string> deleteAllStringAsync(string courseId, string user) {
            return base.Channel.deleteAllStringAsync(courseId, user);
        }
        
        public string deleteAll(courseBackGround.parentReference.parentDeleteAll use) {
            return base.Channel.deleteAll(use);
        }
        
        public System.Threading.Tasks.Task<string> deleteAllAsync(courseBackGround.parentReference.parentDeleteAll use) {
            return base.Channel.deleteAllAsync(use);
        }
    }
}
